import "./styles/global.scss"
// import "bootstrap/dist/css/bootstrap.css"
 
import type { Metadata } from "next";

import Header from "./components/header";
import Navbar from "./components/navbar";


export const metadata : Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {

  return (
    <html lang="en">

      <body> 

      <Header/>

      <Navbar/>

        {children}

      </body>

    </html>
  );
}
