import type { Metadata } from "next";
import Header from "./components/header";
import Navbar from "./components/navbar";
import Hero from './components/hero'
import "./globals.scss";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Header/>
      <Navbar/>
      <Hero/>
        {children}
      </body>
    </html>
  );
}
